### ISSUE TITLE
Your Wordpress Article on DaemonContaxt HELP!

### ISSUE THREAD

**Issue by leifadev** [dpdani/ds-2-assignment#1]
Hello my guy,

I do not speak italian but I will say that was a great guide you made, but I am having one problem and that is using the permissions and being able to write files etc.

I hate to link you to another thing that may seem like a rabbit hole but if you could supervise me here a bit and see what I am doing wrong to be denied permission from interacting with files? I want it to work without have to run chmod/chown to give --6 to a file to make it work like it does without inside the daemon context manager :(

If you see this help if you can or other wise Ima not use it and do something else lol

[https://www.reddit.com/r/learnpython/comments/snx2qk/pythondaemon_daemoncontext_has_errno_13/](https://www.reddit.com/r/learnpython/comments/snx2qk/pythondaemon_daemoncontext_has_errno_13/)

Have a good day! :3

**Comment by dpdani** [comment]
This is clearly not the place to ask such questions.
